#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Ulauncher state=floating border=off
bspc rule -a Kupfer.py border=off



# Border
bspc config focused_border_color        "#9fcc2e"
bspc config normal_border_color         "#44475a"
bspc config active_border_color         "#44475a"



#
# Autostart
#
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh --docky &
# Notifications
/usr/bin/dunst &
dunstctl set-paused true &

# Wallpaper
nitrogen --restore &
# Dex
# dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# GTK settings
# export GTK_THEME=Nordic-bluish-accent
# export GTK4_THEME=Nordic-bluish-accent
gsettings set org.gnome.desktop.interface icon-theme "Nordic-bluish-accent"
gsettings set org.gnome.desktop.interface gtk-theme "vimix-dark-laptop-beryl"
# gsettings set org.gnome.desktop.interface icon-theme "Fantasma-GTK"
gsettings set org.gnome.desktop.interface cursor-theme "Qogir"
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"

# Monitor setup
xrandr --output eDP-1 --primary

# Autostarts
/home/vivien/bin/autosuspend
nm-applet
libinput-gestures
# ulauncher --no-window-shadow --hide-window
# synapse -s &

# cd ~/apps/5e-srd-api && docker-compose up --build # Run the 5e API on startup

# TODO
# aesthetics - so much
# scratchpad
# gestures
# Systemd
# killall -9 emacs
trash ~/.config/emacs/.cache/.emacs.desktop.lock
systemctl start --user emacs &
emacs --fg-daemon &

systemctl start --user cronie &
systemctl start --user spotify-listener &
systemctl start --user onedrive &
systemctl start --user mopidy &
#systemctl restart --user emacs


picom -cb --config ~/.config/picom/picom.conf &

# Swap parens
setxkbmap -option parens:swap_brackets &
